# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("upi", "UPI"),
                    ("card", "Credit/Debit Card"),
                    ("net_banking", "Net Banking"),
                ],
                default="cod",
                max_length=30,
            ),
        ),
    ]
